In [1]:
from __future__ import print_function
import torch

"""
张量学习
"""

'\n张量学习\n'

In [13]:
#打印x的第一列
x = torch.randn(5, 4)
print(x)
print(x[:, 1])
print(x.size())

x  =  x.view(-1,10)
c = x.shape

tensor([[ 1.2405, -1.4155, -1.0716,  0.0255],
        [ 0.7727,  1.0194,  0.0861,  0.9605],
        [ 1.7980, -0.8417, -0.6597,  0.2921],
        [-1.1803,  0.2071, -0.9671,  0.1833],
        [ 0.9041,  1.2528,  0.7225,  2.7032]])
tensor([-1.4155,  1.0194, -0.8417,  0.2071,  1.2528])
torch.Size([5, 4])


In [28]:
# 将 x Torch Tensor转换成NumPy数组
x = torch.randn(3,5)
x+=1
print(x)
x = x.numpy()
print(x)

tensor([[ 0.3896,  1.1393,  2.0394,  1.3877, -0.0297],
        [-0.2299, -0.9294,  1.5241,  0.8195,  0.2001],
        [ 0.0204,  0.6847,  1.0166,  0.8417, -1.3539]])
[[ 0.38963652  1.139321    2.0394287   1.3876772  -0.02971888]
 [-0.2299074  -0.92935646  1.5240564   0.8195133   0.20006967]
 [ 0.02036554  0.6846626   1.016598    0.8416998  -1.35391   ]]


In [33]:
# 把NumPy数组转成Torch Tensor的代码示例为：
import numpy as np
a = np.ones(15)
print(a)
b = torch.from_numpy(a)
b=b.view(-1,3)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
